dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8
  - oraclejdk9

notifications:
  email:
    - acogoluegnes@pivotal.io
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
      - sourceline: 'ppa:deadsnakes/ppa'

    packages:
      - esl-erlang=1:20.3.6
before_install:
  - sudo apt-get update
  - sudo apt-get install python3.7
branches:
  only:
    - master
before_script:
  - ./bin/before_build.sh

script: ./mvnw clean verify -P '!setup-test-node' -Dtravis-ci=true -Drabbitmqctl.bin='rabbitmq/sbin/rabbitmqctl' -Dtest-broker.A.nodename=rabbit@$(hostname)
cache:
  directories:
    - $HOME/.m2
install: true
