dist: trusty
sudo: required

language: java
jdk:
  - oraclejdk8

notifications:
  email:
    - acogoluegnes@pivotal.io
env:
  - PYTHON=python3.7
addons:
  apt:
    sources:
      - sourceline: deb https://packages.erlang-solutions.com/ubuntu trusty contrib
        key_url: https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc
      - sourceline: 'ppa:deadsnakes/ppa'

    packages:
      - esl-erlang=1:21.2.4-1
# because of https://github.com/travis-ci/travis-ci/issues/8906
before_install:
  - sudo apt-get update
  - sudo apt-get install python3.7
  - curl -s https://packagecloud.io/install/repositories/rabbitmq/rabbitmq-server/script.deb.sh | sudo bash
  - sudo mv /opt/jdk_switcher/jdk_switcher.sh /tmp
  - sudo apt-get install rabbitmq-server=3.7.10-1
  - sudo mv /tmp/jdk_switcher.sh /opt/jdk_switcher/
branches:
  only:
    - master
before_script:
  - ./bin/before_build.sh

script: ./mvnw clean verify -P '!setup-test-node' -Dtravis-ci=true -Drabbitmqctl.bin='rabbitmq/sbin/rabbitmqctl' -Dtest-broker.A.nodename=rabbit@$(hostname) -Dtest-client-cert.password= -Dtest-tls-certs.dir=/tmp/tls-gen/basic
cache:
  directories:
    - $HOME/.m2
install: true
