dist: trusty
group: deprecated-2017Q4
sudo: required

language: java
jdk:
  - oraclejdk8

notifications:
  email:
    - acogoluegnes@pivotal.io
services:
  - rabbitmq
branches:
  only:
    - master
before_script:
  - ./bin/install_on_debian.sh
  - ./bin/before_build.sh

script: ./mvnw clean verify -P '!setup-test-node' -Djunit5.exclude.tags='tls,need-rabbitmqctl'
cache:
  directories:
    - $HOME/.m2
install: true
